param(
    [string]$Configuration = 'Release'
)

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$project = Join-Path $projectRoot 'src\A-Note\A-Note.csproj'
$iconGenerator = Join-Path $PSScriptRoot 'Generate-AppIcon.ps1'
$publishDir = Join-Path $projectRoot 'artifacts\publish\win-x64'

if (-not (Get-Command dotnet -ErrorAction SilentlyContinue)) {
    throw '.NET SDK was not found on PATH.'
}
if (-not (Test-Path -LiteralPath $project)) {
    throw "A-Note project file is missing: $project"
}

if (Test-Path -LiteralPath $iconGenerator) {
    # PowerShell script failures propagate as terminating errors.
    & $iconGenerator
}

if (Test-Path -LiteralPath $publishDir) {
    Remove-Item -LiteralPath $publishDir -Recurse -Force
}
New-Item -ItemType Directory -Path $publishDir -Force | Out-Null

Write-Host "Publishing A-Note ($Configuration, win-x64, self-contained)..."
dotnet publish $project `
    -c $Configuration `
    -r win-x64 `
    --self-contained true `
    -p:Platform=x64 `
    -p:PublishSingleFile=false `
    -p:PublishTrimmed=false `
    -p:WindowsAppSDKSelfContained=true `
    -o $publishDir

if ($LASTEXITCODE -ne 0) {
    throw "dotnet publish failed (exit code $LASTEXITCODE)."
}

# Unpackaged WinUI 3 can leave compiled XAML in obj/bin rather than in `dotnet publish -o`.
# Recover the XBFs generated by this exact configuration/runtime.
$xbfSearchRoots = @(
    (Join-Path $projectRoot "src\A-Note\obj\x64\$Configuration"),
    (Join-Path $projectRoot "src\A-Note\bin\x64\$Configuration")
) | Where-Object { Test-Path -LiteralPath $_ }

foreach ($xbf in @('App.xbf', 'MainWindow.xbf')) {
    $target = Join-Path $publishDir $xbf

    if (-not (Test-Path -LiteralPath $target)) {
        $resolved = $xbfSearchRoots |
            ForEach-Object {
                Get-ChildItem -LiteralPath $_ -Filter $xbf -File -Recurse -ErrorAction SilentlyContinue |
                    Where-Object {
                        $_.FullName -match [regex]::Escape('net8.0-windows10.0.19041.0') -and
                        ($_.FullName -match '\\win-x64\\' -or $_.FullName -notmatch '\\win-')
                    }
            } |
            Sort-Object LastWriteTimeUtc -Descending |
            Select-Object -First 1

        if (-not $resolved) {
            throw "Missing $xbf. WinUI did not produce the compiled XAML file in publish, bin, or obj output."
        }

        Copy-Item -LiteralPath $resolved.FullName -Destination $target -Force
        Write-Host "Recovered $xbf from: $($resolved.FullName)"
    }
}

# Generate resources.pri beside the unpackaged executable.
$makePriCandidates = @()

if (${env:ProgramFiles(x86)}) {
    $sdkBinRoot = Join-Path ${env:ProgramFiles(x86)} 'Windows Kits\10\bin'
    if (Test-Path -LiteralPath $sdkBinRoot) {
        $makePriCandidates += Get-ChildItem -LiteralPath $sdkBinRoot -Filter makepri.exe -Recurse -File -ErrorAction SilentlyContinue |
            Where-Object { $_.FullName -match '\\x64\\makepri\.exe$' }
    }
}

if ($env:ProgramFiles) {
    $sdkBinRoot64 = Join-Path $env:ProgramFiles 'Windows Kits\10\bin'
    if (Test-Path -LiteralPath $sdkBinRoot64) {
        $makePriCandidates += Get-ChildItem -LiteralPath $sdkBinRoot64 -Filter makepri.exe -Recurse -File -ErrorAction SilentlyContinue |
            Where-Object { $_.FullName -match '\\x64\\makepri\.exe$' }
    }
}

$makePri = $makePriCandidates |
    Sort-Object {
        $versionText = Split-Path (Split-Path $_.DirectoryName -Parent) -Leaf
        try { [version]$versionText } catch { [version]'0.0' }
    } -Descending |
    Select-Object -First 1

if (-not $makePri) {
    throw 'Windows SDK makepri.exe was not found. Install the Windows 10/11 SDK build tools.'
}

$stage = Join-Path $projectRoot 'artifacts\pri-stage'
if (Test-Path -LiteralPath $stage) {
    Remove-Item -LiteralPath $stage -Recurse -Force
}
New-Item -ItemType Directory -Path $stage -Force | Out-Null

foreach ($xbf in @('App.xbf', 'MainWindow.xbf')) {
    Copy-Item -LiteralPath (Join-Path $publishDir $xbf) -Destination $stage -Force
}

$config = Join-Path $stage 'priconfig.xml'
$pri = Join-Path $stage 'resources.pri'

& $makePri.FullName createconfig /cf $config /dq en-US /o | Out-Null
if ($LASTEXITCODE -ne 0) {
    throw "PRI configuration generation failed (exit code $LASTEXITCODE)."
}

& $makePri.FullName new /pr $stage /cf $config /of $pri /o | Out-Null
if ($LASTEXITCODE -ne 0) {
    throw "PRI generation failed (exit code $LASTEXITCODE)."
}

Copy-Item -LiteralPath $pri -Destination (Join-Path $publishDir 'resources.pri') -Force

$required = @(
    'A-Note.exe',
    'A-Note.dll',
    'App.xbf',
    'MainWindow.xbf',
    'resources.pri'
)

foreach ($file in $required) {
    if (-not (Test-Path -LiteralPath (Join-Path $publishDir $file))) {
        throw "Release publish is incomplete: missing $file."
    }
}

$exe = Get-Item -LiteralPath (Join-Path $publishDir 'A-Note.exe')
if ($exe.Length -eq 0) {
    throw 'Published A-Note.exe is empty.'
}

Write-Host "A-Note publish ready: $publishDir"
Write-Output $publishDir
